export const waecphysics = [
  // TOPIC 1 - Mechanics (20-25% frequency in NECO) - hardest topic ___
  { id: 1, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "***", question: "A particle moves with constant acceleration. If u = 2 m/s, a = 3 m/s² and t = 4 s, find v.", options: ["14 m/s", "12 m/s", "10 m/s", "8 m/s"], answer: 0 },
  { id: 2, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "***", question: "A car covers 100 m in 5 s starting from rest with constant acceleration. Find acceleration.", options: ["8 m/s²", "5 m/s²", "4 m/s²", "10 m/s²"], answer: 2 },
  { id: 3, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "***", question: "Displacement when velocity is v = u + at is given by?", options: ["s = ut + 1/2 at²", "s = vt + 1/2 at²", "s = ut - 1/2 at²", "s = ut"], answer: 0 },
  { id: 4, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "**", question: "Average speed versus average velocity: which is false?", options: ["Average speed is scalar, average velocity is vector", "Average speed can equal magnitude of average velocity", "Average velocity is always positive", "Average speed ≥ |average velocity|"], answer: 2 },
  { id: 5, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "**", question: "If a body moves in a circle at constant speed, its acceleration is:", options: ["Directed toward centre", "Zero", "Tangent to circle", "Backward"], answer: 0 },
  { id: 6, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "**", question: "If displacement is zero but distance is non-zero then the motion is:", options: ["A closed path", "Uniform motion", "Accelerated motion", "Non-uniform"], answer: 0 },
  { id: 7, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "*", question: "If a car moves at 20 m/s for 3 s, distance covered is:", options: ["60 m", "23 m", "17 m", "6.7 m"], answer: 0 },
  { id: 8, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "*", question: "Speed is the rate of change of:", options: ["Distance", "Displacement", "Acceleration", "Momentum"], answer: 0 },
  { id: 9, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "*", question: "Unit of acceleration is:", options: ["m/s²", "m/s", "m", "s²"], answer: 0 },
  { id: 10, topic: "Mechanics - Kinematics", topicDiff: "___", qDiff: "*", question: "When velocity increases with time, acceleration is:", options: ["Positive", "Negative", "Zero", "Undefined"], answer: 0 },

  // TOPIC 2 - Dynamics & Forces (18-22% frequency in NECO) - harder topic __
  { id: 11, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "***", question: "A mass of 5 kg is pulled by a resultant force of 20 N. Find acceleration.", options: ["4 m/s²", "5 m/s²", "3 m/s²", "2 m/s²"], answer: 0 },
  { id: 12, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "***", question: "Coefficient of friction μ if frictional force = 10 N and normal = 20 N?", options: ["0.5", "2", "0.2", "1"], answer: 0 },
  { id: 13, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "***", question: "Newton’s 3rd law states:", options: ["Action and reaction are equal and opposite", "Net force is zero", "Energy is conserved", "Momentum is conserved"], answer: 0 },
  { id: 14, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "**", question: "Weight of a body is:", options: ["mg", "m/g", "m + g", "m-g"], answer: 0 },
  { id: 15, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "**", question: "If resultant force on a body is zero, the body:", options: ["Has constant velocity", "Must be at rest", "Has changing speed", "Has changing direction"], answer: 0 },
  { id: 16, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "**", question: "If mass doubles and force is constant, acceleration:", options: ["Halves", "Doubles", "Same", "Quadruples"], answer: 0 },
  { id: 17, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "*", question: "Unit of force is:", options: ["Newton", "Joule", "Watt", "Pascal"], answer: 0 },
  { id: 18, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "*", question: "Friction always opposes:", options: ["Relative motion", "Gravity", "Normal reaction", "Velocity"], answer: 0 },
  { id: 19, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "*", question: "Tension in a light string is same throughout when:", options: ["Massless string and no friction pulley", "Heavy string", "Frictionful pulley", "Different accelerations"], answer: 0 },
  { id: 20, topic: "Dynamics & Forces", topicDiff: "__", qDiff: "*", question: "Mass × acceleration equals:", options: ["Force", "Momentum", "Speed", "Energy"], answer: 0 },

  // TOPIC 3 - Energy & Work (12-15% frequency in NECO) - hard topic _
  { id: 21, topic: "Energy & Work", topicDiff: "_", qDiff: "***", question: "Work done when a force of 10 N moves object 3 m in direction of force is:", options: ["30 J", "3 J", "13 J", "7 J"], answer: 0 },
  { id: 22, topic: "Energy & Work", topicDiff: "_", qDiff: "***", question: "Kinetic energy of mass 2 kg moving at 3 m/s is:", options: ["9 J", "6 J", "18 J", "3 J"], answer: 0 },
  { id: 23, topic: "Energy & Work", topicDiff: "_", qDiff: "***", question: "Potential energy mgh for m=2 kg, g=10 m/s², h=5 m is:", options: ["100 J", "50 J", "10 J", "200 J"], answer: 0 },
  { id: 24, topic: "Energy & Work", topicDiff: "_", qDiff: "**", question: "Power is the rate of doing:", options: ["Work", "Mass", "Force", "Energy density"], answer: 0 },
  { id: 25, topic: "Energy & Work", topicDiff: "_", qDiff: "**", question: "Unit of energy is:", options: ["Joule", "Newton", "Watt", "Pascal"], answer: 0 },
  { id: 26, topic: "Energy & Work", topicDiff: "_", qDiff: "**", question: "If work done is zero, displacement is:", options: ["Perpendicular to force", "Along force", "Opposite force", "Parallel to force"], answer: 0 },
  { id: 27, topic: "Energy & Work", topicDiff: "_", qDiff: "*", question: "1 kW equals:", options: ["1000 W", "100 W", "10 W", "1 W"], answer: 0 },
  { id: 28, topic: "Energy & Work", topicDiff: "_", qDiff: "*", question: "When energy changes from one form to another, this is called:", options: ["Energy conversion", "Energy loss", "Energy creation", "Energy storage"], answer: 0 },
  { id: 29, topic: "Energy & Work", topicDiff: "_", qDiff: "*", question: "If no non-conservative forces act, mechanical energy is:", options: ["Conserved", "Zero", "Increased", "Undefined"], answer: 0 },
  { id: 30, topic: "Energy & Work", topicDiff: "_", qDiff: "*", question: "Work done by gravity on a body thrown up and back to same point is:", options: ["Zero", "Positive", "Negative", "Depends"], answer: 0 },

  // TOPIC 4 - Waves & Oscillations (10-12% frequency) - harder topic __
  { id: 31, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "***", question: "Wave speed v is given by v = fλ. If f = 500 Hz and λ = 0.5 m, v = ?", options: ["250 m/s", "1000 m/s", "2500 m/s", "50 m/s"], answer: 0 },
  { id: 32, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "***", question: "For simple harmonic motion period T = 2π√(m/k). If m increases, T:", options: ["Increases", "Decreases", "Remains same", "Becomes zero"], answer: 0 },
  { id: 33, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "***", question: "A standing wave has nodes where:", options: ["Displacement is always zero", "Displacement is maximum", "Energy is maximum", "Phase is undefined"], answer: 0 },
  { id: 34, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "**", question: "Frequency unit is:", options: ["Hz", "s", "m", "N"], answer: 0 },
  { id: 35, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "**", question: "If amplitude doubles, energy in SHM:", options: ["Quadruples", "Doubles", "Halves", "Remains same"], answer: 0 },
  { id: 36, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "**", question: "Transverse waves have particle motion:", options: ["Perpendicular to direction of wave", "Parallel to wave", "Circular", "Random"], answer: 0 },
  { id: 37, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "*", question: "Wavelength of visible light is about:", options: ["500 nm", "5 m", "500 mm", "5 nm"], answer: 0 },
  { id: 38, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "*", question: "Resonance occurs when driving frequency equals:", options: ["Natural frequency", "Zero", "Any frequency", "Half frequency"], answer: 0 },
  { id: 39, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "*", question: "Refraction is change of:", options: ["Direction of wave due to media change", "Frequency", "Amplitude only", "Energy creation"], answer: 0 },
  { id: 40, topic: "Waves & Oscillations", topicDiff: "__", qDiff: "*", question: "Echo is an example of:", options: ["Reflection of sound", "Refraction of sound", "Diffraction", "Interference"], answer: 0 },

  // TOPIC 5 - Electricity & Circuits (10-12% frequency) - hardest topic ___
  { id: 41, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "***", question: "Ohm's law: V = IR. If I = 2 A and R = 5 Ω, V = ?", options: ["10 V", "7 V", "3 V", "2.5 V"], answer: 0 },
  { id: 42, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "***", question: "Equivalent resistance of 2 Ω and 3 Ω in series:", options: ["5 Ω", "1.2 Ω", "6 Ω", "0.6 Ω"], answer: 0 },
  { id: 43, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "***", question: "Power dissipated P = IV. If V=12 V and I=0.5 A, P = ?", options: ["6 W", "24 W", "0.6 W", "12 W"], answer: 0 },
  { id: 44, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "**", question: "Current unit is:", options: ["Ampere", "Volt", "Ohm", "Watt"], answer: 0 },
  { id: 45, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "**", question: "A fuse protects a circuit by:", options: ["Melting when current is too high", "Amplifying current", "Reducing voltage", "Balancing charge"], answer: 0 },
  { id: 46, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "**", question: "In a parallel circuit voltage across each branch is:", options: ["Same", "Different", "Zero", "Depends on resistances"], answer: 0 },
  { id: 47, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "*", question: "Conductors allow:", options: ["Free flow of electrons", "No charge movement", "Only heat", "Only light"], answer: 0 },
  { id: 48, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "*", question: "Battery provides:", options: ["Electromotive force (emf)", "Resistance", "Current source only when connected", "Voltage drop only"], answer: 0 },
  { id: 49, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "*", question: "Series circuit has current:", options: ["Same through all components", "Different in each branch", "Zero", "Alternating only"], answer: 0 },
  { id: 50, topic: "Electricity & Circuits", topicDiff: "___", qDiff: "*", question: "SI unit of charge is:", options: ["Coulomb", "Ampere", "Volt", "Ohm"], answer: 0 },

  // TOPIC 6 - Magnetism & Electromagnetism (12-14% frequency) - harder topic __
  { id: 51, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "***", question: "Magnetic field lines outside a bar magnet run from:", options: ["North to South", "South to North", "Center outwards", "Random"], answer: 0 },
  { id: 52, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "***", question: "Motor effect requires current and:", options: ["Magnetic field", "High voltage", "Vacuum", "Static electricity"], answer: 0 },
  { id: 53, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "***", question: "Right-hand rule gives direction of force on a:", options: ["Current-carrying conductor in magnetic field", "Static charge in field", "Light ray", "Sound wave"], answer: 0 },
  { id: 54, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "**", question: "Electromagnet strength increases with:", options: ["Current and coils", "Lower current", "Fewer turns", "No core"], answer: 0 },
  { id: 55, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "**", question: "Magnetic materials are:", options: ["Iron, cobalt, nickel", "Copper, silver", "Plastic, rubber", "Glass, wood"], answer: 0 },
  { id: 56, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "**", question: "A changing magnetic field induces:", options: ["An emf", "Mass", "Temperature rise", "Static charge"], answer: 0 },
  { id: 57, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "*", question: "Permanent magnet has poles:", options: ["North and South", "Only North", "Only South", "No pole"], answer: 0 },
  { id: 58, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "*", question: "Soft iron is used in electromagnets because it is:", options: ["Easily magnetized and demagnetized", "Hard to magnetize", "Expensive", "Insulator"], answer: 0 },
  { id: 59, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "*", question: "Magnetic flux unit is:", options: ["Weber", "Tesla", "Henry", "Ohm"], answer: 0 },
  { id: 60, topic: "Magnetism & Electromagnetism", topicDiff: "__", qDiff: "*", question: "Compass needle aligns with:", options: ["Earth's magnetic field", "Electric field", "Gravitational field", "Temperature gradient"], answer: 0 },

  // TOPIC 7 - Thermodynamics & Heat (10-12% frequency) - hard topic _
  { id: 61, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "***", question: "Specific heat capacity relation Q = mcΔT. If m=2 kg, c=1000 J/kgK, ΔT=2 K, Q = ?", options: ["4000 J", "2000 J", "1000 J", "500 J"], answer: 0 },
  { id: 62, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "***", question: "Absolute zero in Celsius is about:", options: ["-273°C", "-100°C", "0°C", "-373°C"], answer: 0 },
  { id: 63, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "***", question: "Heat transfer by conduction occurs in:", options: ["Solids", "Vacuum", "All cases equally", "Gases only"], answer: 0 },
  { id: 64, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "**", question: "Temperature measures:", options: ["Average kinetic energy of particles", "Total energy", "Mass", "Density"], answer: 0 },
  { id: 65, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "**", question: "Expansion of solids is usually:", options: ["Small", "Large", "Negative", "Non-existent"], answer: 0 },
  { id: 66, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "**", question: "Latent heat is involved when:", options: ["Phase change occurs", "Temperature changes", "Mass changes", "Volume constant"], answer: 0 },
  { id: 67, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "*", question: "Unit of temperature in SI is:", options: ["Kelvin", "Celsius", "Fahrenheit", "Rankine"], answer: 0 },
  { id: 68, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "*", question: "Boiling point of water at sea level in Celsius:", options: ["100°C", "90°C", "212°C", "0°C"], answer: 0 },
  { id: 69, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "*", question: "Convection occurs in:", options: ["Fluids", "Solids only", "Vacuum", "All materials equally"], answer: 0 },
  { id: 70, topic: "Thermodynamics & Heat", topicDiff: "_", qDiff: "*", question: "Thermal equilibrium means:", options: ["Same temperature", "Same pressure", "No motion", "Same mass"], answer: 0 },

  // TOPIC 8 - Optics (8-10% frequency) - harder topic __
  { id: 71, topic: "Optics", topicDiff: "__", qDiff: "***", question: "Law of reflection states angle of incidence equals:", options: ["Angle of reflection", "Normal", "Surface angle", "None"], answer: 0 },
  { id: 72, topic: "Optics", topicDiff: "__", qDiff: "***", question: "Lens that converges parallel rays to a point is:", options: ["Convex lens", "Concave lens", "Plane lens", "Cylindrical lens"], answer: 0 },
  { id: 73, topic: "Optics", topicDiff: "__", qDiff: "***", question: "Colour dispersion in prism results from variation in:", options: ["Refractive index with wavelength", "Mass with wavelength", "Speed only", "Amplitude"], answer: 0 },
  { id: 74, topic: "Optics", topicDiff: "__", qDiff: "**", question: "Real image is formed when rays:", options: ["Converge", "Diverge", "Are parallel", "Are stationary"], answer: 0 },
  { id: 75, topic: "Optics", topicDiff: "__", qDiff: "**", question: "Focal length of a plane mirror is:", options: ["Infinity", "Zero", "Half the radius", "Equal to radius"], answer: 0 },
  { id: 76, topic: "Optics", topicDiff: "__", qDiff: "**", question: "Total internal reflection occurs when light goes from:", options: ["Denser to rarer medium", "Rarer to denser", "Any direction", "Into vacuum"], answer: 0 },
  { id: 77, topic: "Optics", topicDiff: "__", qDiff: "*", question: "Unit of luminous intensity is:", options: ["Candela", "Lumen", "Watt", "Lux"], answer: 0 },
  { id: 78, topic: "Optics", topicDiff: "__", qDiff: "*", question: "Concave mirror can produce:", options: ["Real or virtual images", "Only virtual", "No image", "Only magnified images"], answer: 0 },
  { id: 79, topic: "Optics", topicDiff: "__", qDiff: "*", question: "Thin lens equation is 1/f = 1/v + 1/u. If u = -10 cm and v = 20 cm, f = ?", options: ["13.33 cm", "6.67 cm", "-13.33 cm", "30 cm"], answer: 1 },
  { id: 80, topic: "Optics", topicDiff: "__", qDiff: "*", question: "Speed of light in vacuum is approximately:", options: ["3×10^8 m/s", "3×10^6 m/s", "3×10^5 m/s", "3×10^7 m/s"], answer: 0 },

  // TOPIC 9 - Modern Physics (5-8% frequency) - hard topic _
  { id: 81, topic: "Modern Physics", topicDiff: "_", qDiff: "***", question: "Photoelectric effect proves light can behave as:", options: ["Particle (photon)", "Pure wave", "Magnet", "Sound"], answer: 0 },
  { id: 82, topic: "Modern Physics", topicDiff: "_", qDiff: "***", question: "Electron has charge approximately:", options: ["-1.6×10^-19 C", "1.6×10^-19 C", "-9.1×10^-31 C", "0C"], answer: 0 },
  { id: 83, topic: "Modern Physics", topicDiff: "_", qDiff: "***", question: "Atomic nucleus contains:", options: ["Protons and neutrons", "Electrons", "Photons", "Neutrinos only"], answer: 0 },
  { id: 84, topic: "Modern Physics", topicDiff: "_", qDiff: "**", question: "Radioactivity includes:", options: ["Alpha, beta and gamma decay", "Only alpha", "Only gamma", "Only beta"], answer: 0 },
  { id: 85, topic: "Modern Physics", topicDiff: "_", qDiff: "**", question: "Mass-energy equivalence formula is:", options: ["E = mc²", "F = ma", "V = IR", "p = mv"], answer: 0 },
  { id: 86, topic: "Modern Physics", topicDiff: "_", qDiff: "**", question: "Nucleus radius is of order:", options: ["10^-15 m", "10^-3 m", "1 m", "10^-9 m"], answer: 0 },
  { id: 87, topic: "Modern Physics", topicDiff: "_", qDiff: "*", question: "Photon is a particle of:", options: ["Light", "Mass", "Charge", "Gravity"], answer: 0 },
  { id: 88, topic: "Modern Physics", topicDiff: "_", qDiff: "*", question: "Beta particle is:", options: ["Electron or positron", "Neutron", "Proton", "Alpha particle"], answer: 0 },
  { id: 89, topic: "Modern Physics", topicDiff: "_", qDiff: "*", question: "Half-life is the time for:", options: ["Half the nuclei to decay", "All to decay", "Double to decay", "One quarter to decay"], answer: 0 },
  { id: 90, topic: "Modern Physics", topicDiff: "_", qDiff: "*", question: "Unit of radioactivity is:", options: ["Becquerel", "Curie", "Both A and B", "Sievert"], answer: 2 },

  // TOPIC 10 - Measurement & Units (3-5% frequency) - hard topic _
  { id: 91, topic: "Measurement & Units", topicDiff: "_", qDiff: "***", question: "SI base unit for length is:", options: ["Metre", "Kilogram", "Second", "Ampere"], answer: 0 },
  { id: 92, topic: "Measurement & Units", topicDiff: "_", qDiff: "***", question: "A vernier caliper measures to the nearest:", options: ["0.1 mm (typical)", "1 m", "1 s", "1 kg"], answer: 0 },
  { id: 93, topic: "Measurement & Units", topicDiff: "_", qDiff: "***", question: "Precision differs from accuracy in that precision is about:", options: ["Repeatability", "Correctness", "Range", "Unit"], answer: 0 },
  { id: 94, topic: "Measurement & Units", topicDiff: "_", qDiff: "**", question: "Micrometer screw gauge measures small lengths using:", options: ["Rotational screw", "Laser", "Electric sensor", "Mercury"], answer: 0 },
  { id: 95, topic: "Measurement & Units", topicDiff: "_", qDiff: "**", question: "Order of magnitude of 0.005 m is:", options: ["10^-3 m", "10^3 m", "10^-6 m", "10^-1 m"], answer: 0 },
  { id: 96, topic: "Measurement & Units", topicDiff: "_", qDiff: "**", question: "Calibration adjusts an instrument to ensure:", options: ["Correct readings", "Longer life", "Bigger size", "Faster response"], answer: 0 },
  { id: 97, topic: "Measurement & Units", topicDiff: "_", qDiff: "*", question: "Common unit of pressure is:", options: ["Pascal", "Joule", "Watt", "Newton"], answer: 0 },
  { id: 98, topic: "Measurement & Units", topicDiff: "_", qDiff: "*", question: "Mass measured on a balance compares mass to:", options: ["Standard mass", "Volume", "Density", "Weight"], answer: 0 },
  { id: 99, topic: "Measurement & Units", topicDiff: "_", qDiff: "*", question: "A stopwatch measures:", options: ["Time intervals", "Length", "Mass", "Temperature"], answer: 0 },
  { id: 100, topic: "Measurement & Units", topicDiff: "_", qDiff: "*", question: "SI base unit for electric current is:", options: ["Ampere", "Volt", "Ohm", "Coulomb"], answer: 0 }
];