export const WaecEnglish = [
  // TOPIC 1 - Comprehension (20-25% frequency) - hardest topic ___
  { id: 1, topic: "Comprehension", topicDiff: "___", qDiff: "***", question: "Main idea questions usually ask for the:", options: ["Overall theme of the passage", "Spelling of a word", "Author’s name", "Font used"], answer: 0 },
  { id: 2, topic: "Comprehension", topicDiff: "___", qDiff: "***", question: "Inference questions require you to:", options: ["Read between the lines", "Copy a sentence", "Translate literally", "Ignore passage"], answer: 0 },
  { id: 3, topic: "Comprehension", topicDiff: "___", qDiff: "***", question: "If a word in passage is unfamiliar, you should:", options: ["Use context clues", "Skip passage", "Guess randomly", "Count letters"], answer: 0 },
  { id: 4, topic: "Comprehension", topicDiff: "___", qDiff: "**", question: "Tone of a passage refers to the author’s:", options: ["Attitude", "Font choice", "Paragraph length", "Publication date"], answer: 0 },
  { id: 5, topic: "Comprehension", topicDiff: "___", qDiff: "**", question: "A summary should be:", options: ["Concise and cover main points", "Long and detailed", "Include all examples", "Be word-for-word"], answer: 0 },
  { id: 6, topic: "Comprehension", topicDiff: "___", qDiff: "**", question: "Skimming helps to:", options: ["Get general idea quickly", "Understand every detail", "Correct grammar", "Find spelling errors"], answer: 0 },
  { id: 7, topic: "Comprehension", topicDiff: "___", qDiff: "*", question: "Literal comprehension asks for information that is:", options: ["Stated directly in the text", "Implied", "Unknown", "False"], answer: 0 },
  { id: 8, topic: "Comprehension", topicDiff: "___", qDiff: "*", question: "Contextual meaning is derived from:", options: ["Surrounding text", "Dictionary only", "Author name", "Title only"], answer: 0 },
  { id: 9, topic: "Comprehension", topicDiff: "___", qDiff: "*", question: "A paragraph often contains:", options: ["One main idea", "Many unrelated topics", "Only lists", "Only questions"], answer: 0 },
  { id: 10, topic: "Comprehension", topicDiff: "___", qDiff: "*", question: "To find synonyms use:", options: ["Context or thesaurus", "Random guesses", "Opposite words", "Numbers"], answer: 0 },

  // TOPIC 2 - Cloze Test & Fill-in (18-22% frequency) - harder topic __
  { id: 11, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "***", question: "Choose correct preposition: She is responsible ___ the project.", options: ["for", "to", "with", "on"], answer: 0 },
  { id: 12, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "***", question: "Choose correct form: He ___ to the market yesterday.", options: ["went", "goes", "gone", "going"], answer: 0 },
  { id: 13, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "***", question: "Choose correct article: She adopted ___ dog.", options: ["a", "an", "the", "no article"], answer: 0 },
  { id: 14, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "**", question: "Plural of 'analysis' is:", options: ["analyses", "analysis", "analysises", "analysi"], answer: 0 },
  { id: 15, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "**", question: "Complete: If I ___ you, I would apologize.", options: ["were", "was", "am", "be"], answer: 0 },
  { id: 16, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "**", question: "Choose correct conjunction: He left early ___ he was tired.", options: ["because", "but", "and", "or"], answer: 0 },
  { id: 17, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "*", question: "Opposite of 'ancient' is:", options: ["modern", "old", "aged", "historic"], answer: 0 },
  { id: 18, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "*", question: "We use 'few' with:", options: ["Countable nouns", "Uncountable nouns", "Adjectives", "Verbs"], answer: 0 },
  { id: 19, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "*", question: "Choose correct tense: She ___ already left.", options: ["has", "have", "had", "is"], answer: 0 },
  { id: 20, topic: "Cloze & Fill-in", topicDiff: "__", qDiff: "*", question: "Choose correct pronoun: The book is ___ (I/me).", options: ["mine", "me", "I", "my"], answer: 0 },

  // TOPIC 3 - Vocabulary & Word Meaning (12-15% frequency) - hard topic _
  { id: 21, topic: "Vocabulary", topicDiff: "_", qDiff: "***", question: "Synonym of 'abundant' is:", options: ["plentiful", "rare", "small", "meager"], answer: 0 },
  { id: 22, topic: "Vocabulary", topicDiff: "_", qDiff: "***", question: "Antonym of 'scarce' is:", options: ["plentiful", "scarcer", "rare", "sparse"], answer: 0 },
  { id: 23, topic: "Vocabulary", topicDiff: "_", qDiff: "***", question: "Meaning of 'ambiguous' is:", options: ["Having more than one meaning", "Clear", "Short", "Expensive"], answer: 0 },
  { id: 24, topic: "Vocabulary", topicDiff: "_", qDiff: "**", question: "Which word is a noun: 'decide', 'decision', 'decisive'?", options: ["decision", "decide", "decisive", "deciding"], answer: 0 },
  { id: 25, topic: "Vocabulary", topicDiff: "_", qDiff: "**", question: "Prefix 'un-' means:", options: ["Not", "Very", "Before", "Again"], answer: 0 },
  { id: 26, topic: "Vocabulary", topicDiff: "_", qDiff: "**", question: "Suffix '-ness' turns adjective into a:", options: ["Noun", "Verb", "Adverb", "Pronoun"], answer: 0 },
  { id: 27, topic: "Vocabulary", topicDiff: "_", qDiff: "*", question: "A 'synonym' is a word with:", options: ["Similar meaning", "Opposite meaning", "Same spelling", "Same sound only"], answer: 0 },
  { id: 28, topic: "Vocabulary", topicDiff: "_", qDiff: "*", question: "Word 'benevolent' most nearly means:", options: ["Kind", "Cruel", "Silent", "Active"], answer: 0 },
  { id: 29, topic: "Vocabulary", topicDiff: "_", qDiff: "*", question: "The word 'fragile' describes something:", options: ["Easily broken", "Very heavy", "Bright", "Expensive"], answer: 0 },
  { id: 30, topic: "Vocabulary", topicDiff: "_", qDiff: "*", question: "Homophones are words that:", options: ["Sound the same but differ in meaning/spelling", "Look the same", "Mean the same", "Are antonyms"], answer: 0 },

  // TOPIC 4 - Grammar: Parts of Speech (10-12%) - harder topic __
  { id: 31, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "***", question: "Which is an adjective: 'happy', 'run', 'quickly', 'them'?", options: ["happy", "run", "quickly", "them"], answer: 0 },
  { id: 32, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "***", question: "Which is a conjunction: 'and', 'quick', 'blue', 'run'?", options: ["and", "quick", "blue", "run"], answer: 0 },
  { id: 33, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "***", question: "An adverb modifies a:", options: ["Verb, adjective or other adverb", "Noun only", "Pronoun only", "Conjunction only"], answer: 0 },
  { id: 34, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "**", question: "Pronoun 'they' replaces a:", options: ["Plural noun", "Singular verb", "Adjective", "Adverb"], answer: 0 },
  { id: 35, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "**", question: "Article 'the' is:", options: ["Definite article", "Indefinite article", "Pronoun", "Conjunction"], answer: 0 },
  { id: 36, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "**", question: "Which is a preposition: 'in', 'she', 'happy', 'run'?", options: ["in", "she", "happy", "run"], answer: 0 },
  { id: 37, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "*", question: "Verb 'eat' is of part of speech:", options: ["Verb", "Adjective", "Noun", "Adverb"], answer: 0 },
  { id: 38, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "*", question: "Plural of 'child' is:", options: ["children", "childs", "childes", "child"], answer: 0 },
  { id: 39, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "*", question: "Superlative of 'good' is:", options: ["best", "goodest", "more good", "better"], answer: 0 },
  { id: 40, topic: "Grammar - Parts of Speech", topicDiff: "__", qDiff: "*", question: "Which word is a verb: 'run', 'table', 'blue', 'quick'?", options: ["run", "table", "blue", "quick"], answer: 0 },

  // TOPIC 5 - Grammar: Sentence Structure (10-12%) - hardest topic ___
  { id: 41, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "***", question: "A compound sentence contains:", options: ["Two independent clauses", "One clause only", "Only fragments", "No verbs"], answer: 0 },
  { id: 42, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "***", question: "A complex sentence contains:", options: ["An independent and a dependent clause", "Two independent clauses only", "Only phrases", "No punctuation"], answer: 0 },
  { id: 43, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "***", question: "Identify subject in 'The cat chased the mouse.'", options: ["The cat", "The mouse", "Chased", "The"], answer: 0 },
  { id: 44, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "**", question: "Direct speech uses:", options: ["Quotation marks", "No punctuation", "Brackets only", "Parentheses only"], answer: 0 },
  { id: 45, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "**", question: "Passive voice of 'She wrote a letter' is:", options: ["A letter was written by her", "She was written by a letter", "A letter wrote her", "She wrote"], answer: 0 },
  { id: 46, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "**", question: "Imperative sentence gives:", options: ["Command or request", "Question", "Description", "Explanation"], answer: 0 },
  { id: 47, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "*", question: "Question tag for 'You are coming, ___?' is:", options: ["aren't you", "isn't you", "do you", "will you"], answer: 0 },
  { id: 48, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "*", question: "Relative pronoun 'who' refers to:", options: ["People", "Things", "Places", "Numbers"], answer: 0 },
  { id: 49, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "*", question: "Conditional sentence type 0 expresses:", options: ["General truths", "Impossible events", "Future unreal", "Past regrets"], answer: 0 },
  { id: 50, topic: "Grammar - Sentence Structure", topicDiff: "___", qDiff: "*", question: "Coordinating conjunctions include:", options: ["and, but, or", "because, although", "if, unless", "after, before"], answer: 0 },

  // TOPIC 6 - Summary & Note-making (12-14%) - harder topic __
  { id: 51, topic: "Summary & Note-making", topicDiff: "__", qDiff: "***", question: "A good summary should be:", options: ["Concise and include main points", "Long and detailed", "Include every example", "Be identical to passage"], answer: 0 },
  { id: 52, topic: "Summary & Note-making", topicDiff: "__", qDiff: "***", question: "Effective note-making uses:", options: ["Headings and bullet points", "Full paragraphs only", "Random words", "Decorations"], answer: 0 },
  { id: 53, topic: "Summary & Note-making", topicDiff: "__", qDiff: "***", question: "When summarizing, you should avoid:", options: ["Personal opinion insertion", "Main ideas", "Titles", "Key dates"], answer: 0 },
  { id: 54, topic: "Summary & Note-making", topicDiff: "__", qDiff: "**", question: "Short-hand in note-making helps to:", options: ["Save time", "Confuse reader", "Make text longer", "Lose meaning"], answer: 0 },
  { id: 55, topic: "Summary & Note-making", topicDiff: "__", qDiff: "**", question: "Summaries are usually:", options: ["Shorter than original", "Longer than original", "Same length", "Useless"], answer: 0 },
  { id: 56, topic: "Summary & Note-making", topicDiff: "__", qDiff: "**", question: "When making notes, highlight:", options: ["Key words and ideas", "Every sentence", "All punctuation", "Speaker names only"], answer: 0 },
  { id: 57, topic: "Summary & Note-making", topicDiff: "__", qDiff: "*", question: "Abbreviations in notes are used to:", options: ["Speed writing", "Create errors", "Add decoration", "Replace meaning"], answer: 0 },
  { id: 58, topic: "Summary & Note-making", topicDiff: "__", qDiff: "*", question: "Mind maps are a form of:", options: ["Visual note-making", "Formal essays", "Long reports", "Spoken exam"], answer: 0 },
  { id: 59, topic: "Summary & Note-making", topicDiff: "__", qDiff: "*", question: "Topic sentences usually occur at:", options: ["Start of a paragraph", "End of book", "Randomly", "Only titles"], answer: 0 },
  { id: 60, topic: "Summary & Note-making", topicDiff: "__", qDiff: "*", question: "Paraphrasing means:", options: ["Rewriting in your own words", "Copying verbatim", "Translating to another language", "Summing numbers"], answer: 0 },

  // TOPIC 7 - Functional Writing (Letters, Forms) (10-12%) - hard topic _
  { id: 61, topic: "Functional Writing", topicDiff: "_", qDiff: "***", question: "Formal letter should begin with:", options: ["Your address and date", "Slang greeting", "Emoji", "Unrelated quote"], answer: 0 },
  { id: 62, topic: "Functional Writing", topicDiff: "_", qDiff: "***", question: "A complaint letter should:", options: ["State problem and request remedy", "Be abusive", "Be vague", "Contain no purpose"], answer: 0 },
  { id: 63, topic: "Functional Writing", topicDiff: "_", qDiff: "***", question: "In application letters include:", options: ["Qualifications and reason for applying", "Irrelevant jokes", "Long stories", "No contact details"], answer: 0 },
  { id: 64, topic: "Functional Writing", topicDiff: "_", qDiff: "**", question: "Salutation in formal letter is usually:", options: ["Dear Sir/Madam", "Hey buddy", "Yo!", "Hiya"], answer: 0 },
  { id: 65, topic: "Functional Writing", topicDiff: "_", qDiff: "**", question: "Closing a formal letter use:", options: ["Yours faithfully/sincerely", "See ya", "Later", "Cheers"], answer: 0 },
  { id: 66, topic: "Functional Writing", topicDiff: "_", qDiff: "**", question: "Forms require:", options: ["Clear and accurate information", "Long essays", "Filler words", "Stories"], answer: 0 },
  { id: 67, topic: "Functional Writing", topicDiff: "_", qDiff: "*", question: "Enclose documents when:", options: ["Requested or necessary", "Never", "Always", "Randomly"], answer: 0 },
  { id: 68, topic: "Functional Writing", topicDiff: "_", qDiff: "*", question: "Tone in a letter should be:", options: ["Appropriate to purpose", "Always humorous", "Always angry", "Always casual"], answer: 0 },
  { id: 69, topic: "Functional Writing", topicDiff: "_", qDiff: "*", question: "Dates in letters are written to the:", options: ["Top right (commonly)", "Bottom left", "Middle only", "Not included"], answer: 0 },
  { id: 70, topic: "Functional Writing", topicDiff: "_", qDiff: "*", question: "Enclosures are indicated by:", options: ["'Encl.' or 'Enc.'", "No sign", "Signature only", "Header only"], answer: 0 },

  // TOPIC 8 - Essay & Composition (8-10%) - harder topic __
  { id: 71, topic: "Essay & Composition", topicDiff: "__", qDiff: "***", question: "A good essay introduction should:", options: ["Introduce topic and thesis", "Give every detail", "Be one word", "Copy the question"], answer: 0 },
  { id: 72, topic: "Essay & Composition", topicDiff: "__", qDiff: "***", question: "Body paragraphs should:", options: ["Each focus on one main idea", "Mix many ideas", "Be unrelated", "Contain no examples"], answer: 0 },
  { id: 73, topic: "Essay & Composition", topicDiff: "__", qDiff: "***", question: "Conclusion should:", options: ["Summarize and close argument", "Introduce new ideas", "Be longer than body", "Be vague"], answer: 0 },
  { id: 74, topic: "Essay & Composition", topicDiff: "__", qDiff: "**", question: "Coherence in writing means:", options: ["Logical flow of ideas", "Many long words", "Random order", "Incomplete sentences"], answer: 0 },
  { id: 75, topic: "Essay & Composition", topicDiff: "__", qDiff: "**", question: "Examples in essays provide:", options: ["Support for claims", "Distraction", "Spelling errors", "Incorrect facts"], answer: 0 },
  { id: 76, topic: "Essay & Composition", topicDiff: "__", qDiff: "**", question: "First person narrative uses pronoun:", options: ["I", "You", "He", "They"], answer: 0 },
  { id: 77, topic: "Essay & Composition", topicDiff: "__", qDiff: "*", question: "Topic sentence is usually at:", options: ["Start of paragraph", "End of book", "Title only", "Middle of text always"], answer: 0 },
  { id: 78, topic: "Essay & Composition", topicDiff: "__", qDiff: "*", question: "Formal essays avoid:", options: ["Slang and contractions", "Clear structure", "Good examples", "Accurate facts"], answer: 0 },
  { id: 79, topic: "Essay & Composition", topicDiff: "__", qDiff: "*", question: "Drafting before final copy helps to:", options: ["Improve quality", "Decrease clarity", "Make it worse", "Add errors"], answer: 0 },
  { id: 80, topic: "Essay & Composition", topicDiff: "__", qDiff: "*", question: "Topic choice should be:", options: ["Relevant and manageable", "Random and impossible", "Too broad always", "Too narrow always"], answer: 0 },

  // TOPIC 9 - Oral & Phonetics (5-8%) - hard topic _
  { id: 81, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "***", question: "Phoneme is:", options: ["Smallest unit of sound", "Letter only", "Meaning unit", "Sentence"], answer: 0 },
  { id: 82, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "***", question: "Stress in a word affects its:", options: ["Pronunciation and meaning", "Color", "Length only", "Font"], answer: 0 },
  { id: 83, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "***", question: "Intonation in a question often rises at the:", options: ["End", "Start", "Middle", "Never"], answer: 0 },
  { id: 84, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "**", question: "Consonants are speech sounds produced by:", options: ["Obstruction of airflow", "Open vocal tract", "Whistling only", "Silence"], answer: 0 },
  { id: 85, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "**", question: "Vowels are produced with:", options: ["Open vocal tract", "No vocal cords", "No airflow", "Only nasal sound"], answer: 0 },
  { id: 86, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "**", question: "Plosive consonants include:", options: ["p, b, t, d", "m, n", "s, z", "l, r"], answer: 0 },
  { id: 87, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "*", question: "IPA is used to represent:", options: ["Pronunciation", "Grammar", "Spelling", "Meaning"], answer: 0 },
  { id: 88, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "*", question: "Homographs are words that:", options: ["Same spelling, different meaning/pronunciation", "Same sound only", "Different meaning but same sound", "Have no meaning"], answer: 0 },
  { id: 89, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "*", question: "Pitch refers to how:", options: ["High or low a voice sounds", "Fast speech only", "Volume only", "Grammar"], answer: 0 },
  { id: 90, topic: "Oral & Phonetics", topicDiff: "_", qDiff: "*", question: "Fluency in speaking is:", options: ["Smooth and natural speech", "Very slow speech", "Monotone reading", "Only loudness"], answer: 0 },

  // TOPIC 10 - Literature (3-5% frequency) - hard topic _
  { id: 91, topic: "Literature", topicDiff: "_", qDiff: "***", question: "A simile compares using:", options: ["like or as", "Only verbs", "No comparison", "Numbers"], answer: 0 },
  { id: 92, topic: "Literature", topicDiff: "_", qDiff: "***", question: "Metaphor directly compares two things without:", options: ["using like or as", "Meaning", "Words", "Imagery"], answer: 0 },
  { id: 93, topic: "Literature", topicDiff: "_", qDiff: "***", question: "Personification gives human traits to:", options: ["Non-human things", "People only", "Animals only", "Places only"], answer: 0 },
  { id: 94, topic: "Literature", topicDiff: "_", qDiff: "**", question: "Theme of a poem is its:", options: ["Central idea", "Rhyme scheme", "Meter only", "Font"], answer: 0 },
  { id: 95, topic: "Literature", topicDiff: "_", qDiff: "**", question: "Protagonist in a story is the:", options: ["Main character", "Villain always", "Narrator always", "Minor character"], answer: 0 },
  { id: 96, topic: "Literature", topicDiff: "_", qDiff: "**", question: "Irony is when outcome is:", options: ["Opposite of expectation", "Exactly expected", "Predictable", "Useless"], answer: 0 },
  { id: 97, topic: "Literature", topicDiff: "_", qDiff: "*", question: "Stanza in poetry is like a:", options: ["Paragraph", "Sentence", "Word", "Letter"], answer: 0 },
  { id: 98, topic: "Literature", topicDiff: "_", qDiff: "*", question: "Rhyme scheme is pattern of:", options: ["End sounds", "Capital letters", "Paragraphs", "Punctuation"], answer: 0 },
  { id: 99, topic: "Literature", topicDiff: "_", qDiff: "*", question: "Alliteration repeats:", options: ["Initial consonant sounds", "Vowel sounds only", "Sentence length", "Paragraphs"], answer: 0 },
  { id: 100, topic: "Literature", topicDiff: "_", qDiff: "*", question: "A ballad is typically a:", options: ["Narrative poem", "Technical manual", "Novel", "Dictionary entry"], answer: 0 }
];