export const WaecChemistry = [
  // TOPIC 1 - Atomic Structure & Periodicity (20-25% frequency) - hardest topic ___
  { id: 1, topic: "Atomic Structure", topicDiff: "___", qDiff: "***", question: "Number of protons defines the:", options: ["Atomic number", "Mass number", "Isotope", "Ion"], answer: 0 },
  { id: 2, topic: "Atomic Structure", topicDiff: "___", qDiff: "***", question: "Electron configuration of O (Z=8) is:", options: ["1s2 2s2 2p4", "1s2 2s2 2p6", "1s2 2s1 2p5", "1s2 2s2"], answer: 0 },
  { id: 3, topic: "Atomic Structure", topicDiff: "___", qDiff: "***", question: "Isotopes are atoms with same protons but different:", options: ["Neutrons", "Electrons", "Charge", "Atomic number"], answer: 0 },
  { id: 4, topic: "Atomic Structure", topicDiff: "___", qDiff: "**", question: "Mass number equals:", options: ["Protons + neutrons", "Atomic number", "Electrons", "Protons - neutrons"], answer: 0 },
  { id: 5, topic: "Atomic Structure", topicDiff: "___", qDiff: "**", question: "Valence electrons determine:", options: ["Chemical reactivity", "Mass", "Density", "Boiling point"], answer: 0 },
  { id: 6, topic: "Atomic Structure", topicDiff: "___", qDiff: "**", question: "Relative atomic mass is weighted average of:", options: ["Isotopic masses", "Proton masses only", "Electron masses only", "Ion masses"], answer: 0 },
  { id: 7, topic: "Atomic Structure", topicDiff: "___", qDiff: "*", question: "Proton charge is:", options: ["+1 e", "-1 e", "0", "+2 e"], answer: 0 },
  { id: 8, topic: "Atomic Structure", topicDiff: "___", qDiff: "*", question: "Electron mass is roughly:", options: ["9.11×10^-31 kg", "1.67×10^-27 kg", "1.67×10^-26 kg", "1.0×10^-3 kg"], answer: 0 },
  { id: 9, topic: "Atomic Structure", topicDiff: "___", qDiff: "*", question: "Chemical symbol for sodium is:", options: ["Na", "S", "So", "Sd"], answer: 0 },
  { id: 10, topic: "Atomic Structure", topicDiff: "___", qDiff: "*", question: "Group number in periodic table gives:", options: ["Valence electrons count", "Atomic mass", "Neutron number", "Isotope count"], answer: 0 },

  // TOPIC 2 - Bonding & Structure (18-22% frequency) - harder topic __
  { id: 11, topic: "Bonding & Structure", topicDiff: "__", qDiff: "***", question: "Covalent bond is formed by:", options: ["Sharing of electrons", "Transfer of protons", "Sharing of protons", "Ionic attraction"], answer: 0 },
  { id: 12, topic: "Bonding & Structure", topicDiff: "__", qDiff: "***", question: "Ionic compounds tend to have:", options: ["High melting points", "Low melting points", "No crystalline structure", "Low solubility in water"], answer: 0 },
  { id: 13, topic: "Bonding & Structure", topicDiff: "__", qDiff: "***", question: "Metallic bonding explains:", options: ["Electrical conductivity of metals", "Brittleness of ceramics", "Insulation", "Gas behavior"], answer: 0 },
  { id: 14, topic: "Bonding & Structure", topicDiff: "__", qDiff: "**", question: "Electronegativity trend increases across a period:", options: ["True", "False", "Sometimes", "Never"], answer: 0 },
  { id: 15, topic: "Bonding & Structure", topicDiff: "__", qDiff: "**", question: "A polar covalent bond has:", options: ["Unequal sharing of electrons", "Equal sharing", "Ionic transfer", "No electrons"], answer: 0 },
  { id: 16, topic: "Bonding & Structure", topicDiff: "__", qDiff: "**", question: "Network covalent solid example:", options: ["Diamond", "NaCl", "Water", "Ammonia"], answer: 0 },
  { id: 17, topic: "Bonding & Structure", topicDiff: "__", qDiff: "*", question: "Lewis dot structures show:", options: ["Valence electrons", "Protons only", "Neutrons only", "Nucleus size"], answer: 0 },
  { id: 18, topic: "Bonding & Structure", topicDiff: "__", qDiff: "*", question: "Bond order in O2 is:", options: ["2", "1", "3", "0"], answer: 0 },
  { id: 19, topic: "Bonding & Structure", topicDiff: "__", qDiff: "*", question: "Ionic bond forms between:", options: ["Metal and non-metal", "Two metals", "Two non-metals", "Noble gases"], answer: 0 },
  { id: 20, topic: "Bonding & Structure", topicDiff: "__", qDiff: "*", question: "Hydrogen bond is strongest between:", options: ["H and F/O/N", "H and C", "H and H", "H and He"], answer: 0 },

  // TOPIC 3 - Stoichiometry & Calculations (12-15% frequency) - hard topic _
  { id: 21, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "***", question: "Molar mass of H2O (g/mol) approx:", options: ["18", "17", "16", "20"], answer: 0 },
  { id: 22, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "***", question: "1 mole contains how many particles (Avogadro)?", options: ["6.02×10^23", "6.02×10^22", "1×10^23", "3.0×10^8"], answer: 0 },
  { id: 23, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "***", question: "If 2H2 + O2 → 2H2O, mole ratio H2:O2 is:", options: ["2:1", "1:1", "1:2", "3:2"], answer: 0 },
  { id: 24, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "**", question: "Empirical formula gives:", options: ["Simplest ratio of atoms", "Exact molecular weight", "Physical state", "Boiling point"], answer: 0 },
  { id: 25, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "**", question: "Concentration in mol/dm³ sometimes called:", options: ["Molarity", "Normality", "Molality", "Percentage"], answer: 0 },
  { id: 26, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "**", question: "Limiting reagent is:", options: ["Reactant that runs out first", "Reactant in excess", "Product", "Catalyst"], answer: 0 },
  { id: 27, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "*", question: "Relative molecular mass symbol is:", options: ["Mr", "Ar", "Na", "M"], answer: 0 },
  { id: 28, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "*", question: "Percent yield = (actual/theoretical) ×:", options: ["100%", "10%", "50%", "1%"], answer: 0 },
  { id: 29, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "*", question: "1 dm³ equals:", options: ["1 litre", "1 m³", "1000 mL", "100 mL"], answer: 0 },
  { id: 30, topic: "Stoichiometry & Calculations", topicDiff: "_", qDiff: "*", question: "Gas at STP: 1 mole occupies approximately:", options: ["22.4 L", "1 L", "10 L", "100 L"], answer: 0 },

  // TOPIC 4 - Acids, Bases & Salts (10-12%) - harder topic __
  { id: 31, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "***", question: "pH of neutral solution at 25°C is:", options: ["7", "0", "14", "1"], answer: 0 },
  { id: 32, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "***", question: "Strong acid example:", options: ["HCl", "CH3COOH", "H2CO3", "NH3"], answer: 0 },
  { id: 33, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "***", question: "Base turns red litmus to:", options: ["Blue", "Red", "Green", "No change"], answer: 0 },
  { id: 34, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "**", question: "Salt formed from neutralization of acid and base is usually:", options: ["Ionic compound", "Covalent gas", "Metal", "Polymer"], answer: 0 },
  { id: 35, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "**", question: "pOH + pH equals approximately:", options: ["14 (at 25°C)", "7", "0", "1"], answer: 0 },
  { id: 36, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "**", question: "Indicator that is pink in acid and blue in base is:", options: ["Phenolphthalein", "Methyl orange", "Litmus", "Bromothymol blue"], answer: 0 },
  { id: 37, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "*", question: "Neutralization reaction produces salt and:", options: ["Water", "Oxygen", "Hydrogen", "Carbon dioxide"], answer: 0 },
  { id: 38, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "*", question: "A substance with pH < 7 is:", options: ["Acidic", "Basic", "Neutral", "Salt"], answer: 0 },
  { id: 39, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "*", question: "Ammonia is a:", options: ["Base", "Acid", "Salt", "Neutral gas"], answer: 0 },
  { id: 40, topic: "Acids, Bases & Salts", topicDiff: "__", qDiff: "*", question: "Concentrated acid means:", options: ["High amount of acid per volume", "High purity", "High temperature", "Diluted"], answer: 0 },

  // TOPIC 5 - Chemical Energetics (10-12%) - hardest topic ___
  { id: 41, topic: "Chemical Energetics", topicDiff: "___", qDiff: "***", question: "Exothermic reaction releases:", options: ["Heat", "Cold", "Mass", "Light only"], answer: 0 },
  { id: 42, topic: "Chemical Energetics", topicDiff: "___", qDiff: "***", question: "Endothermic reaction absorbs:", options: ["Heat", "Light only", "No energy", "Mass"], answer: 0 },
  { id: 43, topic: "Chemical Energetics", topicDiff: "___", qDiff: "***", question: "Standard enthalpy change of combustion is usually negative because:", options: ["Heat is released", "Heat is absorbed", "Mass lost", "Work is done"], answer: 0 },
  { id: 44, topic: "Chemical Energetics", topicDiff: "___", qDiff: "**", question: "Activation energy is energy needed to:", options: ["Start a reaction", "Finish a reaction", "Neutralize acid", "Make salt"], answer: 0 },
  { id: 45, topic: "Chemical Energetics", topicDiff: "___", qDiff: "**", question: "Catalyst affects reaction by:", options: ["Lowering activation energy", "Increasing enthalpy change", "Changing reactants", "Removing heat"], answer: 0 },
  { id: 46, topic: "Chemical Energetics", topicDiff: "___", qDiff: "**", question: "Bond breaking is generally:", options: ["Endothermic", "Exothermic", "Neutral", "Impossible"], answer: 0 },
  { id: 47, topic: "Chemical Energetics", topicDiff: "___", qDiff: "*", question: "Heat is measured in:", options: ["Joules", "Kelvin", "Moles", "Litres"], answer: 0 },
  { id: 48, topic: "Chemical Energetics", topicDiff: "___", qDiff: "*", question: "Thermochemistry studies:", options: ["Heat changes in reactions", "Color changes", "Pressure changes only", "Formulas"], answer: 0 },
  { id: 49, topic: "Chemical Energetics", topicDiff: "___", qDiff: "*", question: "Enthalpy is symbolized by:", options: ["H", "E", "S", "G"], answer: 0 },
  { id: 50, topic: "Chemical Energetics", topicDiff: "___", qDiff: "*", question: "ΔH negative indicates:", options: ["Exothermic", "Endothermic", "Neutral", "Impossible"], answer: 0 },

  // TOPIC 6 - Organic Chemistry (12-14%) - harder topic __
  { id: 51, topic: "Organic Chemistry", topicDiff: "__", qDiff: "***", question: "Functional group in alcohol is:", options: ["-OH", "-COOH", "-NH2", "-CHO"], answer: 0 },
  { id: 52, topic: "Organic Chemistry", topicDiff: "__", qDiff: "***", question: "General formula for alkanes is:", options: ["C_nH_{2n+2}", "C_nH_{2n}", "C_nH_{2n-2}", "C_nH_{n}"], answer: 0 },
  { id: 53, topic: "Organic Chemistry", topicDiff: "__", qDiff: "***", question: "Isomerism is same formula but different:", options: ["Structure", "Mass", "Charge", "Boiling point only"], answer: 0 },
  { id: 54, topic: "Organic Chemistry", topicDiff: "__", qDiff: "**", question: "Methane has how many hydrogen atoms?", options: ["4", "2", "3", "1"], answer: 0 },
  { id: 55, topic: "Organic Chemistry", topicDiff: "__", qDiff: "**", question: "Ethene contains a:", options: ["Double bond", "Triple bond", "Aromatic ring", "No bond"], answer: 0 },
  { id: 56, topic: "Organic Chemistry", topicDiff: "__", qDiff: "**", question: "Carboxylic acid ends with functional group:", options: ["-COOH", "-OH", "-NH2", "-Cl"], answer: 0 },
  { id: 57, topic: "Organic Chemistry", topicDiff: "__", qDiff: "*", question: "Aromatic compound example:", options: ["Benzene", "Ethane", "Methanol", "Sodium chloride"], answer: 0 },
  { id: 58, topic: "Organic Chemistry", topicDiff: "__", qDiff: "*", question: "Polymerization makes:", options: ["Large molecules from small monomers", "Small molecules from large ones", "Ions", "Metals"], answer: 0 },
  { id: 59, topic: "Organic Chemistry", topicDiff: "__", qDiff: "*", question: "Alcohol can be oxidized to:", options: ["Aldehyde or ketone", "Salt", "Metal", "Gas"], answer: 0 },
  { id: 60, topic: "Organic Chemistry", topicDiff: "__", qDiff: "*", question: "Saturated hydrocarbon means:", options: ["Single bonds only", "Double bonds", "Triple bonds", "Aromatic only"], answer: 0 },

  // TOPIC 7 - Inorganic Chemistry (10-12%) - hard topic _
  { id: 61, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "***", question: "Transition elements are found in which block?", options: ["d-block", "s-block", "p-block", "f-block"], answer: 0 },
  { id: 62, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "***", question: "Salt of Na+ and Cl- is called:", options: ["Sodium chloride", "Sodium oxide", "Hydrochloric acid", "Sodium hydroxide"], answer: 0 },
  { id: 63, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "***", question: "Oxidation state of oxygen in most compounds is:", options: ["-2", "-1", "+2", "0"], answer: 0 },
  { id: 64, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "**", question: "Metallic oxides are usually:", options: ["Basic", "Acidic", "Neutral", "Explosive"], answer: 0 },
  { id: 65, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "**", question: "A salt that conducts electricity when molten is:", options: ["Ionic compound", "Covalent compound", "Polymer", "Gas"], answer: 0 },
  { id: 66, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "**", question: " amphoteric oxides react with:", options: ["Acids and bases", "Only acids", "Only bases", "Only water"], answer: 0 },
  { id: 67, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "*", question: "Rust is hydrated form of:", options: ["Iron(III) oxide", "Copper oxide", "Aluminium oxide", "Zinc oxide"], answer: 0 },
  { id: 68, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "*", question: "Group 1 metals are called:", options: ["Alkali metals", "Alkaline earth metals", "Halogens", "Noble gases"], answer: 0 },
  { id: 69, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "*", question: "Halogens are normally:", options: ["Reactive non-metals", "Inert gases", "Metals", "Metalloids"], answer: 0 },
  { id: 70, topic: "Inorganic Chemistry", topicDiff: "_", qDiff: "*", question: "Most reactive metal in group 1 is:", options: ["Francium (or Cesium)", "Lithium", "Sodium", "Potassium"], answer: 0 },

  // TOPIC 8 - Equilibrium (8-10%) - harder topic __
  { id: 71, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "***", question: "Le Chatelier’s principle predicts shift when:", options: ["System stressed", "System cooled only", "Reaction stops", "Equilibrium unchanged"], answer: 0 },
  { id: 72, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "***", question: "Kc for a reaction depends on:", options: ["Temperature only", "Pressure only", "Concentration only", "Catalyst only"], answer: 0 },
  { id: 73, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "***", question: "At equilibrium forward and backward rates are:", options: ["Equal", "Zero", "Different", "Infinite"], answer: 0 },
  { id: 74, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "**", question: "Adding inert gas at constant volume affects equilibrium:", options: ["No effect", "Shifts right", "Shifts left", "Removes equilibrium"], answer: 0 },
  { id: 75, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "**", question: "Increase in pressure favours side with:", options: ["Fewer moles of gas", "More moles of gas", "No change", "Higher temp"], answer: 0 },
  { id: 76, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "**", question: "Equilibrium constant Kp uses:", options: ["Partial pressures", "Concentrations", "Masses", "Volumes"], answer: 0 },
  { id: 77, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "*", question: "Dynamic equilibrium means:", options: ["Rates equal but reactions continue", "No reaction", "Only forward reaction", "Only backward reaction"], answer: 0 },
  { id: 78, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "*", question: "Catalyst effect on K: ", options: ["No change in K", "Increases K", "Decreases K", "Makes infinite"], answer: 0 },
  { id: 79, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "*", question: "Heterogeneous equilibrium involves:", options: ["Different phases", "Same phase only", "Only gases", "Only liquids"], answer: 0 },
  { id: 80, topic: "Chemical Equilibrium", topicDiff: "__", qDiff: "*", question: "Equilibrium position near reactants means K is:", options: ["Small (<1)", "Large (>1)", "Equal to 1", "Undefined"], answer: 0 },

  // TOPIC 9 - Electrochemistry & Redox (5-8%) - hard topic _
  { id: 81, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "***", question: "Oxidation is:", options: ["Loss of electrons", "Gain of electrons", "Loss of protons", "Gain of neutrons"], answer: 0 },
  { id: 82, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "***", question: "Cathode in electrolysis is where:", options: ["Reduction occurs", "Oxidation occurs", "No reaction", "Gas formed only"], answer: 0 },
  { id: 83, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "***", question: "Galvanic cell converts chemical energy to:", options: ["Electrical energy", "Heat only", "Light", "Sound"], answer: 0 },
  { id: 84, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "**", question: "Anode in galvanic cell is:", options: ["Negative electrode (oxidation)", "Positive electrode", "Neutral", "Salt bridge"], answer: 0 },
  { id: 85, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "**", question: "Salt bridge function is to:", options: ["Maintain charge balance", "Provide reactant", "Remove electrons", "Heat the cell"], answer: 0 },
  { id: 86, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "**", question: "Electroplating uses:", options: ["Electrolysis", "Combustion", "Distillation", "Filtration"], answer: 0 },
  { id: 87, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "*", question: "Reduction half-reaction gains:", options: ["Electrons", "Protons", "Neutrons", "Mass"], answer: 0 },
  { id: 88, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "*", question: "Standard electrode potential is measured under:", options: ["Standard conditions", "Any conditions", "Vacuum only", "High pressure only"], answer: 0 },
  { id: 89, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "*", question: "Corrosion is essentially:", options: ["Oxidation of metal", "Reduction of metal", "Neutralization", "Polymerization"], answer: 0 },
  { id: 90, topic: "Electrochemistry & Redox", topicDiff: "_", qDiff: "*", question: "Faraday’s laws relate charge to:", options: ["Amount of substance deposited", "Color change", "Temperature", "Pressure"], answer: 0 },

  // TOPIC 10 - Practical & Analytical Chemistry (3-5%) - hard topic _
  { id: 91, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "***", question: "Titration is used to find concentration by reacting with:", options: ["A standard solution", "Heat", "Light", "Filter paper"], answer: 0 },
  { id: 92, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "***", question: "Indicator shows end point by:", options: ["Colour change", "Exothermic change", "Mass change", "Precipitation only"], answer: 0 },
  { id: 93, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "***", question: "Chromatography separates mixtures based on:", options: ["Affinity for stationary/mobile phase", "Color only", "Smell", "pH only"], answer: 0 },
  { id: 94, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "**", question: "pH meter measures:", options: ["pH (hydrogen ion concentration)", "Mass", "Viscosity", "Conductivity"], answer: 0 },
  { id: 95, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "**", question: "Qualitative analysis identifies:", options: ["Which ions are present", "Exact amounts", "Molar mass", "Boiling point"], answer: 0 },
  { id: 96, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "**", question: "Gravimetric analysis is based on measuring:", options: ["Mass of precipitate", "Color intensity", "pH", "Temperature"], answer: 0 },
  { id: 97, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "*", question: "A burette is used to deliver:", options: ["Measured volumes of liquid", "Solid samples", "Gaseous samples", "Powders"], answer: 0 },
  { id: 98, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "*", question: "Filter paper separates:", options: ["Insoluble solids from liquids", "Gases from liquids", "All solutes", "Ions from solvent"], answer: 0 },
  { id: 99, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "*", question: "Boiling point elevation depends on:", options: ["Solute concentration", "Colour", "pH", "Pressure only"], answer: 0 },
  { id: 100, topic: "Practical & Analytical Chemistry", topicDiff: "_", qDiff: "*", question: "Desiccator is used to:", options: ["Keep samples dry", "Heat samples", "Mix reagents", "Grind solids"], answer: 0 }
];